language: ruby
sudo: required
rvm:
- 2.2.2
python:
- 3.4
addons:
  firefox: "50.0"
branches:
  only:
    - master
    - /quarter\d*/
before_install:
- mysql -e "create database IF NOT EXISTS transam_funding_testing;" -uroot
- wget https://github.com/mozilla/geckodriver/releases/download/v0.11.1/geckodriver-v0.11.1-linux64.tar.gz
- mkdir geckodriver
- tar -xzf geckodriver-v0.11.1-linux64.tar.gz -C geckodriver
- export PATH=$PATH:$PWD/geckodriver
- sudo apt-get update
- sudo apt-get install libgeos-dev libproj-dev
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sudo apt-get install -qq python-six
- sudo apt-get install libquantlib0-dev
- sudo pip install -r spec/support/python_requirements.txt
before_script:
- bundle update transam_core transam_transit transam_accounting transam_cpt
- cp spec/dummy/config/database.travis.yml spec/dummy/config/database.yml
script:
- bundle exec rake app:transam_funding:prepare_rspec
- bundle exec rspec
- cd spec/python_unittest/
# - python -m unittest bucket_creation_form
