language: ruby
rvm:
- 2.1.1
branches:
  only:
  - master
env:
- TEST_COMMAND=bundle exec rspec
- TEST_COMMAND=python -m unittest discover
before_install:
- mysql -e "create database IF NOT EXISTS transam_funding_testing;" -uroot
- pip install -r spec/support/python_requirements.txt
before_script:
- bundle update transam_core transam_transit transam_accounting transam_cpt
- cp spec/dummy/config/database.travis.yml spec/dummy/config/database.yml
script:
- bundle exec rake app:transam_funding:prepare_rspec
- bundle exec rspec
- $TEST_COMMAND
