language: ruby
rvm:
- 2.5.3
services:
  - mysql
branches:
  only:
    - master
    - /quarter\d*/
    - develop
    - /2.\d*.\d*/
before_install:
- mysql -e "create database IF NOT EXISTS transam_funding_testing;" -uroot
before_script:
- bundle update transam_core transam_transit transam_accounting transam_cpt
- cp spec/dummy/config/database.travis.yml spec/dummy/config/database.yml
script:
- bundle exec rake app:transam_funding:prepare_rspec
- bundle exec rspec
bundler_args: --without not_travis
