language: ruby
rvm:
- 2.1.1
branches:
  only:
  - master
before_script:
- bundle update transam_core transam_transit transam_accounting transam_cpt
- cp spec/dummy/config/database.travis.yml spec/dummy/config/database.yml
script:
- bundle exec rake app:transam_funding:prepare_rspec_from_canon_schema
- bundle exec rspec
before_install:
- mysql -e "create database IF NOT EXISTS transam_funding_testing;" -uroot
